# Base image
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 80
HEALTHCHECK --interval=30s --timeout=10s --retries=3 \
    CMD curl -f http://localhost/health || exit 1

# Copy and build the project
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["RatingService/RatingService.csproj", "RatingService/"]
COPY ["ServiceProviderRatingNuget/RatingNotificationNuget.csproj", "RatingNotificationNuget/"]
RUN dotnet restore "RatingService/RatingService.csproj"
COPY . .
WORKDIR "/src/RatingService"
RUN dotnet build "RatingService.csproj" -c Release -o /app/build

# Publish the project
FROM build AS publish
RUN dotnet publish "RatingService.csproj" -c Release -o /app/publish

# Final stage/image
FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "RatingService.dll"]
